In [1]:
import pandas as pnd #para manejar el dataframe
import numpy as np #para abrir el csv
import matplotlib.pyplot as plt #para graficar 
import sklearn as sk #para normalizar los datos

In [52]:
X = pnd.read_csv('incidenciaMunicipal_FINAL.csv')
X.head()

Unnamed: 0  CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  \
0           0        1        1        6        15           16      4   
1           1        1        1        6        15           17      9   
2           2        1        1        6        15           18      4   
3           3        1        1        6        15           19      0   
4           4        1        1        6        15           20     34   

   FEBRERO  MARZO  ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  \
0        3      0      7     4      6      4       3           4        1   
1       10     10     11    11      6     10      18           8        3   
2        1      5      3     0      1      1       4           2        5   
3        0      0      0     1      0      0       0           0        0   
4       32     46     44    49     34     49      56          34       24   

   NOVIEMBRE  DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH  
0          4          7             43                 2  
1         14         14            115                 2  
2          6          4             32                 2  
3          1          0              2                 2  
4         49         32            449                 2

In [53]:
X.drop('Unnamed: 0',1,inplace=True)

In [54]:
X.head()

CVE_ENT  CVE_MUN  CVE_MOD  CVE_TIPO  CVE_SUBTIPO  ENERO  FEBRERO  MARZO  \
0        1        1        6        15           16      4        3      0   
1        1        1        6        15           17      9       10     10   
2        1        1        6        15           18      4        1      5   
3        1        1        6        15           19      0        0      0   
4        1        1        6        15           20     34       32     46   

   ABRIL  MAYO  JUNIO  JULIO  AGOSTO  SEPTIEMBRE  OCTUBRE  NOVIEMBRE  \
0      7     4      6      4       3           4        1          4   
1     11    11      6     10      18           8        3         14   
2      3     0      1      1       4           2        5          6   
3      0     1      0      0       0           0        0          1   
4     44    49     34     49      56          34       24         49   

   DICIEMBRE  TOTAL_DELITOS  VIVIENDA_ENDUTIH  
0          7             43                 2  
1         14            115                 2  
2          4             32                 2  
3          0              2                 2  
4         32            449                 2

In [55]:
y = X[['TOTAL_DELITOS']]
y.head()

TOTAL_DELITOS
0             43
1            115
2             32
3              2
4            449

In [56]:
X = X[X.columns.difference(['TOTAL_DELITOS'])]
X.head()

ABRIL  AGOSTO  CVE_ENT  CVE_MOD  CVE_MUN  CVE_SUBTIPO  CVE_TIPO  DICIEMBRE  \
0      7       3        1        6        1           16        15          7   
1     11      18        1        6        1           17        15         14   
2      3       4        1        6        1           18        15          4   
3      0       0        1        6        1           19        15          0   
4     44      56        1        6        1           20        15         32   

   ENERO  FEBRERO  JULIO  JUNIO  MARZO  MAYO  NOVIEMBRE  OCTUBRE  SEPTIEMBRE  \
0      4        3      4      6      0     4          4        1           4   
1      9       10     10      6     10    11         14        3           8   
2      4        1      1      1      5     0          6        5           2   
3      0        0      0      0      0     1          1        0           0   
4     34       32     49     34     46    49         49       24          34   

   VIVIENDA_ENDUTIH  
0                 2  
1                 2  
2                 2  
3                 2  
4                 2

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

In [28]:
X_train.shape

(42926, 18)

In [29]:
X_test.shape

(10732, 18)

In [30]:
y_train.shape

(42926, 1)

In [42]:
y_test.shape

(10732, 1)

In [32]:
y.head()

TOTAL_DELITOS
0             43
1            115
2             32
3              2
4            449

In [33]:
X_test.head()

ABRIL  AGOSTO  CVE_ENT  CVE_MOD  CVE_MUN  CVE_SUBTIPO  CVE_TIPO  \
53533      9      16       32        6       56           16        16   
8821      15      12        9        3       13           10         9   
7625       0       0        6        8        4           10        16   
21761      1       0       15        2       84           10         6   
49947      0       0       31        2       32           10         7   

       DICIEMBRE  ENERO  FEBRERO  JULIO  JUNIO  MARZO  MAYO  NOVIEMBRE  \
53533          8      8       10     12     12     15    20          6   
8821          19      8       10     20     10     14     9         16   
7625           0      0        0      0      0      0     0          0   
21761          0      0        0      0      0      0     0          0   
49947          0      0        0      0      0      0     0          0   

       OCTUBRE  SEPTIEMBRE  VIVIENDA_ENDUTIH  
53533        8           7                 0  
8821        17          16                 0  
7625         0           0                 2  
21761        1           0                 3  
49947        0           0                 0

## Gaussian Naive Bayes

In [34]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (brier_score_loss, precision_score, recall_score,
                             f1_score)

In [35]:
clf_gNB = GaussianNB()
clf_gNB.fit(X_train, y_train)

/home/desarrollo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

## Predicciones

In [37]:
y_pred = clf_gNB.predict(X_test)
y_pred

array([116, 150,   0, ...,   0,  10,   2])

## El performance que nos da es de 78%, es un número bueno

In [38]:
performance = clf_gNB.score(X_test,y_test)
performance*100

78.68058143868804

In [39]:
o = clf_gNB.predict(X_test)
o = (o).T
o = o.tolist()

In [45]:
y_test_per = y_test.TOTAL_DELITOS.tolist()
hits=0
for i in range(1, len(o)):
    if o[i] == y_test_per[i]:
        hits += 1
        
print('performance: ', round((hits/len(o))*100),'%')

performance:  79 %


## SVM Support Vector Machine

In [57]:
from sklearn import svm

In [ ]:
clf = svm.SVR()
clf.fit(X_train, y_train) 

In [ ]:
clf_p = clf.predict(X_test)

In [ ]:
performance = clf.score(X_test,y_test)
performance*100

##  Desicion Tree Regressor

In [21]:
from sklearn import tree

In [22]:
clf_tree = tree.DecisionTreeRegressor()

In [23]:
clf_tree.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [26]:
y_pred_tree = clf_tree.predict(X_test)
y_pred_tree

array([113., 175.,   0., ...,   0.,   8.,   3.])

In [27]:
performance = clf_tree.score(X_test,y_test)
performance*100

97.91701945985612

In [30]:
o = clf_tree.predict(X_test)
o = (o).T
o = o.tolist()

In [31]:
y_test_per = y_test.TOTAL_DELITOS.tolist()
hits=0
for i in range(1, len(o)):
    if o[i] == y_test_per[i]:
        hits += 1
        
print('performance: ', round((hits/len(o))*100),'%')

performance:  81 %


## Random forest regressor

In [34]:
from sklearn.ensemble import RandomForestRegressor

In [36]:
regr = RandomForestRegressor(random_state=0)
regr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [37]:
regr_pred = regr.predict(X_test)
regr_pred

array([119.6, 151.1,   0. , ...,   0. ,  11.3,   3.4])

In [38]:
o = regr.predict(X_test)
o = (o).T
o = o.tolist()

In [39]:
y_test_per = y_test.TOTAL_DELITOS.tolist()
hits=0
for i in range(1, len(o)):
    if o[i] == y_test_per[i]:
        hits += 1
        
print('performance: ', round((hits/len(o))*100),'%')

performance:  76 %


## GradientBoostingRegressor

In [40]:
from sklearn.ensemble import GradientBoostingRegressor

In [41]:
est = GradientBoostingRegressor()
est.fit(X_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

In [42]:
est_pred = est.predict(X_test)
est_pred

array([1.34379607e+02, 1.59463405e+02, 1.14950659e-01, ...,
       1.14950659e-01, 1.07035820e+01, 2.45675930e+00])

In [43]:
per = est.score(X_test,y_test)
per*100

99.58941640399297

In [54]:
o = est.predict(X_test)
o = (o).T
o = o.tolist()

y_test_per = y_test.TOTAL_DELITOS.tolist()
hits=0
for i in range(1, len(o)):
    if o[i] == y_test_per[i]:
        hits += 1
        
print('performance: ', round((hits/len(o))*100),'%')

performance:  0 %


## KNeighborsRegressor

In [47]:
from sklearn.neighbors import KNeighborsRegressor

In [48]:
neigh = KNeighborsRegressor()
neigh.fit(X_train, y_train) 

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [49]:
neigh_y = neigh.predict(X_test)
neigh_y

array([115.4, 152.8,   0. , ...,   0. ,   4.6,   0.2])

In [51]:
neigh.score(X_test,y_test) * 100

98.9731944112608

In [55]:
o = neigh.predict(X_test)
o = (o).T
o = o.tolist()

y_test_per = y_test.TOTAL_DELITOS.tolist()
hits=0
for i in range(1, len(o)):
    if o[i] == y_test_per[i]:
        hits += 1
        
print('performance: ', round((hits/len(o))*100),'%')

performance:  55 %
